name: Build Docker Images 

on:
  push:
    branches:
      - main  # Trigger pipeline on push to the main branch
  pull_request:
    branches:
      - main  # Trigger pipeline on pull requests to the main branch

jobs:
  # Build Docker images
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build Docker images
        run: |
          docker build -t user-service ./user-service
          docker build -t product-service ./product-catalog-service
          docker build -t cart-service ./shopping-cart-service
          docker build -t order-service ./order-service
          docker build -t payment-service ./payment-service
          docker build -t notification-service ./notification-service