name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger pipeline on push to the main branch
  pull_request:
    branches:
      - main  # Trigger pipeline on pull requests to the main branch

jobs:
  # Build Docker images
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build Docker images
        run: |
          docker build -t user-service ./user-service
          docker build -t product-service ./product-catalog-service
          docker build -t cart-service ./shopping-cart-service
          docker build -t order-service ./order-service
          docker build -t payment-service ./payment-service
          docker build -t notification-service ./notification-service

  # Run tests
  test:
    runs-on: ubuntu-latest
    needs: build  # Only run tests after the build job

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          cd user-service && npm install 
          cd product-catalog-service && npm install 
          cd shopping-cart-service && npm install 
          cd order-service && npm install 
          cd payment-service && npm install 
          cd notification-service && npm install 

      - name: Run tests
        run: |
          cd user-service && npm run test 
          cd product-catalog-service && npm run test 
          cd shopping-cart-service && npm run test 
          cd order-service && npm run test 
          cd payment-service && npm run test 
          cd notification-service && npm run test 